userLocation: "{Amit: 'New Jersey', Joy: 'Illinois', Mainak: 'Connecticut'}"

my:
 name: Deeksha
 gender: FEMALE
 age:  30
 list:
    value: one,two,three
 greetings: Hello Kingshuk from the config server
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6999/eureka
  

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@kingsdatabase.cbxkwasywxio.us-east-1.rds.amazonaws.com:1521:kingsdb
    username: personalfinance_konvergion
    password: Iofdtiger#1086
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        dialect: org.hibernate.dialect.Oracle12cDialect
