userLocation: "{Amit: 'New Jersey', Joy: 'Illinois', Mainak: 'Connecticut'}"

person.name=Kingshuk

my:
 name: Deeksha
 gender: FEMALE
 age:  30
 list:
    value: one,two,three
 greetings: Hello ${person.name} from the config server
  
  

management.endpoints.web.exposure.include: "*"
