
spring:
  application:
    name: microservice-course-api-gateway
  cloud:
    config:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8011
