spring:
  application:
    name: microservice-course-budget-management
  cloud:
    config:
      enabled: true

server:
  port: 9900
  

transactions_url: http://konvergion-transaction-management/transactions
