userLocation: "{Amit: 'New Jersey', Joy: 'Illinois', Mainak: 'Connecticut'}"

my:
 name: Amit Biswas
 gender: MALE
 age:  32
 list:
    value: one,two,three

management.endpoints.web.exposure.include: "*"
